name: Bug Report
description: File a bug report to help us improve Sigma Auto Clicker
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve it.
  - type: input
    id: version
    attributes:
      label: Sigma Auto Clicker Version
      description: What version are you using? (Check `src/__init__.py` or executable version)
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 10
        - Windows 11
        - Other
      description: What OS are you running?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear description of what the bug is
      placeholder: e.g., Clicking stops after 10 seconds
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Start the app
        2. Set CPS to 20
        3. Press F6
        4. Observe crash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: e.g., Continuous clicking at 20 CPS
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Attach logs from `logs/app.log` or screenshots (drag and drop)
      placeholder: Paste logs here or describe screenshot
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (e.g., antivirus, admin mode)