name: Feature Request
description: Suggest an idea for Sigma Auto Clicker
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea clearly.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: e.g., Add support for randomized click intervals
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: e.g., Useful for games requiring variable click patterns
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternatives you've tried?
      placeholder: e.g., Manually adjusting CPS
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details or mockups?