name: Auto Merge

on:
  workflow_run:
    workflows: ["CI"]  # Wait for CI workflow (which includes coverage)
    types: [completed]
    branches: [main, dev]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v4
    
    - name: Auto-merge PR
      uses: pascalgn/automerge-action@v0.16.4
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        MERGE_METHOD: merge
        MERGE_LABELS: "dev"  # Merge all PRs
        MERGE_DELETE_BRANCH: true
