name: automerge
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, ready_for_review, reopened]
    branches:
      - dev  # Restrict to PRs targeting dev branch
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
jobs:
  validate-and-automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout PR head
          fetch-depth: 0  # Full history for version checks

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate version.txt
        run: |
          if [[ ! -f version.txt ]]; then
            echo "❌ Error: version.txt not found in repository root."
            exit 1
          fi
          VERSION=$(cat version.txt)
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Error: version.txt does not contain a valid semver (e.g., 1.0.0). Found: $VERSION"
            exit 1
          fi
          echo "✅ Version $VERSION validated successfully."

      - name: Test launcher script
        run: |
          if [[ ! -f launcher.py ]]; then
            echo "❌ Error: launcher.py not found."
            exit 1
          fi
          python launcher.py --version-only  # Assumes launcher.py supports a version-only flag
        env:
          PYTHONUNBUFFERED: 1  # Ensure real-time output

      - name: Run automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          MERGE_LABELS: automerge  # Explicitly require 'automerge' label
          MERGE_METHOD: splash  # Use merge commit (can change to squash/rebase)
          MERGE_RETRIES: 3  # Retry on transient failures
          MERGE_RETRY_WAIT: 5000  # Wait 5s between retries