name: Auto Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [main, master]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.draft == false
    steps:
    - name: Auto-merge PR
      uses: pascalgn/automerge-action@v0.16.4
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        MERGE_METHOD: merge
        MERGE_LABELS: ""
        MERGE_REMOVE_LABELS: ""
        MERGE_DELETE_BRANCH: true
        MERGE_REQUIRED_APPROVALS: 0
        MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
        MERGE_RETRY_COUNT: 3
        MERGE_RETRY_WAIT: 10