name: Auto Merge

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto merge if labeled
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: rebase # or 'merge' or 'rebase'
          MERGE_LABELS: "automerge"
          MERGE_COMMIT_MESSAGE: "Auto merged PR #{{ pullRequest.number }}"