name: automerge
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, ready_for_review, reopened]
    branches:
      - stable  # Updated from dev, assuming dev doesn't exist
      - dev
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
jobs:
  validate-and-automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_RETRIES: 3
          MERGE_RETRY_WAIT: 5000