name: Auto Merge

on:
  pull_request:
    branches: [ main, dev ]
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    needs: [ coverage ]  # Wait for coverage.yml
    if: github.event.pull_request.draft == false && env.AUTO_MERGE_TOKEN != ''  # Skip if draft or token unset
    steps:
    - uses: actions/checkout@v4
    
    - name: Auto-merge PR
      uses: pascalgn/automerge-action@v0.16.4
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        MERGE_METHOD: merge
        MERGE_LABELS: ""  # Merge all PRs
        MERGE_DELETE_BRANCH: true