name: Coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false  # Allow all jobs to complete
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock  # Ensure pytest-cov and pytest-mock
    
    - name: Install xvfb for GUI tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb  # For PySide6/pyautogui
    
    - name: Run tests with coverage
      run: |
        # Exit gracefully if tests/ or src/ is missing
        if [ ! -d "tests" ] || [ ! -d "src" ]; then echo "Tests or src directory missing"; exit 0; fi
        xvfb-run pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11' && env.CODECOV_TOKEN != ''  # Only for 3.11, skip if token unset
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Requires token in Secrets
      with:
        file: ./coverage.xml
        fail_ci_if_error: false  # Prevent CI failure if Codecov upload fails