name: Coverage

on:
  push:
    branches: [ stable, dev ]
  pull_request:
    branches: [ stable, dev ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock  # Fix: Add pytest-cov
    
    - name: Install xvfb for GUI tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb  # Fix: Support PySide6/pyautogui
    
    - name: Run tests with coverage
      run: |
        if [ ! -d "tests" ] || [ ! -d "src" ]; then echo "Tests or src directory missing"; exit 0; fi
        xvfb-run pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11' && env.CODECOV_TOKEN != ''
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Upload coverage to Codecov (no token)
      if: matrix.python-version == '3.11' && env.CODECOV_TOKEN == ''
      uses: codecov/codecov-action@v4 # Fix: Upload even without token
      with:
        fail_ci_if_error: false
        flags: no-token
        name: codecov-no-token
        file: ./coverage.xml
      env:
        CODECOV_TOKEN: ''

    - name: Upload coverage to Codecov (all versions)
      if: matrix.python-version != '3.11'
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        flags: other-versions
        name: codecov-other-versions