name: Sigma Auto Clicker Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.8)

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      # Checkout the repository at the specific tag
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for version tagging

      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Cache pip dependencies for faster builds

      # Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install runtime dependencies (create requirements.txt in repo root if missing)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Fallback: Install known core dependencies
            pip install PySide6 pyautogui keyboard requests psutil
          fi
          # Install build tool
          pip install pyinstaller
        shell: bash  # Consistent shell on Windows

      # Build the executable with PyInstaller
      - name: Build Sigma Auto Clicker executable
        run: |
          # Assume main script is 'main.py' - adjust if needed (e.g., 'sigma_autoclicker.py')
          pyinstaller --onefile --windowed --name "Sigma-Auto-Clicker" \
            --icon=icon.ico \  # Optional: Add if you have an icon file
            --add-data "path/to/appdata;appdata" \  # Optional: Bundle data files if needed
            main.py
        continue-on-error: false
        shell: bash

      # Upload build artifacts for debugging (optional)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sigma-autoclicker-build
          path: |
            dist/Sigma-Auto-Clicker.exe
            build/
          retention-days: 30

      # Create and publish GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Sigma-Auto-Clicker.exe
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for Sigma Auto Clicker ${{ github.ref_name }}.
            
            ## Changes
            - Built with Python 3.11 and PyInstaller.
            - Executable: [Sigma-Auto-Clicker.exe](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/Sigma.Auto.Clicker.exe)
            
            ## Installation
            1. Download the .exe file.
            2. Run it (admin privileges may be required for full functionality).
            
            ## Requirements
            - Windows 10+.
            - Python dependencies bundled inside the exe.
            
            For issues, open a GitHub issue.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
