name: Sigma Auto Clicker Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags (e.g., v1.0.8)

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      # Checkout the repository at the specific tag
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for version tagging

      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Cache pip dependencies for faster builds

      # Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: bash # Ensure consistent shell behavior on Windows

      # Build the executable with PyInstaller
      - name: Build Sigma Auto Clicker executable
        run: python setup.py
        continue-on-error: false # Fail the job if the build step fails

      # Create and publish GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Sigma-Auto-Clicker.exe
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for Sigma Auto Clicker ${{ github.ref_name }}.
            Built executable: Sigma-Auto-Clicker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
