name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'  # pre-release tags like v1.0.0-beta.1

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine release type
        id: release_type
        run: |
          if [[ "${{ github.ref_name }}" =~ -[a-zA-Z] ]]; then
            echo "type=pre-release" >> $GITHUB_OUTPUT
          else
            echo "type=release" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.release_type.outputs.type == 'pre-release' }}
          generateReleaseNotes: true