name: Publish to WinGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-winget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Validate version
        id: validate
        run: |
          VERSION_FILE="version.txt"  # Adjust to Sigma-Auto-Clicker/version.txt if needed
          if [[ ! -f "$VERSION_FILE" ]]; then
            echo "❌ Error: $VERSION_FILE not found in repository"
            exit 1
          fi
          VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
            echo "❌ Error: Invalid version format in $VERSION_FILE. Expected semver (e.g., 1.0.0 or 1.0.0.0). Found: $VERSION"
            exit 1
          fi
          TAG_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          if [[ "$TAG_VERSION" != "$VERSION" ]]; then
            echo "❌ Error: Release tag ($TAG_VERSION) does not match $VERSION_FILE ($VERSION)"
            exit 1
          fi
          FORMATTED_VERSION=$(echo "$VERSION" | awk -F. '{printf "%d.%d.%d.%d", $1, $2, $3, ($4 ? $4 : 0)}')
          echo "version=$FORMATTED_VERSION" >> $GITHUB_OUTPUT
          echo "✅ Validated version: $FORMATTED_VERSION"

      - name: Create WinGet manifest
        run: |
          mkdir -p manifests
          cat <<EOF > manifests/installer.yaml
          PackageIdentifier: MrAndiGamesDev.SigmaAutoClicker
          PackageVersion: ${{ steps.validate.outputs.version }}
          PackageName: Sigma Auto Clicker
          Publisher: MrAndiGamesDev
          License: MIT
          ShortDescription: A Python-based auto-clicker tool.
          InstallerType: custom
          Installers:
          - InstallerUrl: https://github.com/MrAndiGamesDev/Sigma-Auto-Clicker/archive/refs/tags/v${{ github.event.release.tag_name }}.zip
            InstallerSwitches:
              Custom: pip install --user .
          ManifestType: installer
          ManifestVersion: 1.6.0
          EOF
          echo "✅ Created manifest: manifests/installer.yaml"

      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: MrAndiGamesDev.SigmaAutoClicker
          version: ${{ steps.validate.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}