name: Publish to WinGet

on:
  release:
    types: [published]

jobs:
  winget-release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: extract-version
        run: |
          # Extract version from tag (e.g., v1.2.3 or v1.2.3.4) and ensure 4 components
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//' | awk -F. '{printf "%d.%d.%d.%d", $1, $2, $3, ($4 ? $4 : 0)}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: MrAndiGamesDev.SigmaAutoClicker
          version: ${{ steps.extract-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}